use_frameworks!

target 'Mac_Example' do
  pod 'Mac', :path => '../'

  target 'Mac_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
